//! In-memory clipboard history.
//!
//! Watches the **system pasteboard**, not the PTY. That is the whole point:
//! `pbcopy` from Claude's Bash tool, ⌘C in xterm.js and a copy from Safari all
//! land in the same place, so one observer covers every source without going
//! anywhere near architectural decision #2 (never parse terminal output).
//!
//! macOS exposes no pasteboard-change notification, so we poll
//! `NSPasteboard.changeCount` — a monotonic integer bumped on every write by
//! any process. Polling *that* rather than the contents costs an integer read
//! per tick and correctly catches copying the same text twice, which
//! content-diffing cannot distinguish from nothing happening.
//!
//! Nothing is written to disk. The ring dies with the process (PRP 022).

use std::collections::VecDeque;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{LazyLock, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};

const POLL_MS: u64 = 500;
const MAX_ENTRIES: usize = 10;

/// Per-entry cap. Generous for the emails, snippets and command output this
/// exists to catch, while keeping the worst case bounded at 640KB resident.
const MAX_TEXT_BYTES: usize = 64 * 1024;

/// Pasteboard type markers whose presence means "do not record this".
///
/// The first three are the nspasteboard.org convention that password managers
/// and clipboard utilities agree on; the fourth is 1Password's own marker,
/// which predates it. Missing one of these means quietly capturing a password
/// into a dropdown anyone walking past can read, so the match is deliberately
/// case-insensitive — a marker that fails to match fails in the wrong
/// direction.
const SKIP_MARKERS: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
];

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct ClipEntry {
    pub id: u64,
    pub text: String,
    pub copied_at_ms: u64,
    /// The source text exceeded `MAX_TEXT_BYTES` and `text` is a prefix.
    pub truncated: bool,
}

static HISTORY: LazyLock<Mutex<VecDeque<ClipEntry>>> =
    LazyLock::new(|| Mutex::new(VecDeque::new()));

/// Recording is on by default; the frontend restores the user's choice at
/// boot. While off we keep tracking `changeCount` but never read content, so
/// re-enabling does not backfill whatever was copied in between.
static ENABLED: AtomicBool = AtomicBool::new(true);

/// Our own id sequence rather than reusing `changeCount`, so entry identity
/// does not depend on a platform counter's semantics.
static NEXT_ID: AtomicU64 = AtomicU64::new(1);

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// True when any pasteboard type marks this write as not-to-be-recorded.
pub(crate) fn should_skip(types: &[String]) -> bool {
    types
        .iter()
        .any(|t| SKIP_MARKERS.iter().any(|m| t.eq_ignore_ascii_case(m)))
}

/// Reject whitespace-only copies and cap the rest. Returns the stored text
/// and whether it was cut short.
pub(crate) fn normalize(text: &str) -> Option<(String, bool)> {
    if text.trim().is_empty() {
        return None;
    }
    if text.len() <= MAX_TEXT_BYTES {
        return Some((text.to_string(), false));
    }
    // Back off to a char boundary at or below the cap — slicing mid-codepoint
    // panics.
    let mut end = MAX_TEXT_BYTES;
    while end > 0 && !text.is_char_boundary(end) {
        end -= 1;
    }
    Some((text[..end].to_string(), true))
}

/// Newest-first insertion. Re-copying something already held promotes it
/// instead of producing a duplicate row, which is what every clipboard
/// manager does and what makes the 10-entry cap useful rather than a log.
pub(crate) fn insert_entry(ring: &mut VecDeque<ClipEntry>, entry: ClipEntry) {
    if let Some(pos) = ring.iter().position(|e| e.text == entry.text) {
        ring.remove(pos);
    }
    ring.push_front(entry);
    while ring.len() > MAX_ENTRIES {
        ring.pop_back();
    }
}

#[tauri::command]
pub fn clipboard_history_list() -> Vec<ClipEntry> {
    HISTORY
        .lock()
        .map(|h| h.iter().cloned().collect())
        .unwrap_or_default()
}

#[tauri::command]
pub fn clipboard_history_clear() {
    if let Ok(mut h) = HISTORY.lock() {
        h.clear();
    }
}

#[tauri::command]
pub fn clipboard_history_set_enabled(enabled: bool) {
    ENABLED.store(enabled, Ordering::Relaxed);
}

/// Spawn the poller. Safe to call once at boot; does nothing off macOS.
pub fn install(app: AppHandle) {
    #[cfg(target_os = "macos")]
    std::thread::spawn(move || poll_loop(app));

    #[cfg(not(target_os = "macos"))]
    let _ = app;
}

#[cfg(target_os = "macos")]
fn poll_loop(app: AppHandle) {
    // Seed from the current count so whatever is already on the pasteboard at
    // launch is not recorded as if the user had just copied it.
    let mut last = read_change_count().unwrap_or(0);
    loop {
        std::thread::sleep(Duration::from_millis(POLL_MS));
        let Some(count) = read_change_count() else {
            continue;
        };
        if count == last {
            continue;
        }
        last = count;
        if !ENABLED.load(Ordering::Relaxed) {
            continue;
        }
        let Some(raw) = read_pasteboard_string() else {
            continue;
        };
        let Some((text, truncated)) = normalize(&raw) else {
            continue;
        };
        let entry = ClipEntry {
            id: NEXT_ID.fetch_add(1, Ordering::Relaxed),
            text,
            copied_at_ms: now_ms(),
            truncated,
        };
        if let Ok(mut h) = HISTORY.lock() {
            insert_entry(&mut h, entry.clone());
        }
        let _ = app.emit("clipboard:new", entry);
    }
}

#[cfg(target_os = "macos")]
fn read_change_count() -> Option<i64> {
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::NSPasteboard;

    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();
        Some(pb.changeCount() as i64)
    })
}

/// Read the pasteboard as plain text, unless it carries a marker asking not to
/// be recorded.
#[cfg(target_os = "macos")]
fn read_pasteboard_string() -> Option<String> {
    use objc2::rc::autoreleasepool;
    use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};

    autoreleasepool(|_| {
        let pb = NSPasteboard::generalPasteboard();

        let types: Vec<String> = pb
            .types()
            .map(|arr| arr.iter().map(|t| t.to_string()).collect())
            .unwrap_or_default();
        if should_skip(&types) {
            return None;
        }

        let string_type = unsafe { NSPasteboardTypeString };
        pb.stringForType(string_type).map(|s| s.to_string())
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(id: u64, text: &str) -> ClipEntry {
        ClipEntry {
            id,
            text: text.to_string(),
            copied_at_ms: 0,
            truncated: false,
        }
    }

    #[test]
    fn concealed_writes_are_never_recorded() {
        // The case that matters: a password manager's copy must not survive
        // into the dropdown.
        assert!(should_skip(&[
            "public.utf8-plain-text".into(),
            "org.nspasteboard.ConcealedType".into(),
        ]));
        assert!(should_skip(&["com.agilebits.onepassword".into()]));
        assert!(should_skip(&["org.nspasteboard.TransientType".into()]));
        assert!(should_skip(&["org.nspasteboard.AutoGeneratedType".into()]));
    }

    #[test]
    fn marker_matching_ignores_case() {
        // An app that spells the marker differently must still be honored —
        // failing to match here leaks a secret.
        assert!(should_skip(&["ORG.NSPASTEBOARD.CONCEALEDTYPE".into()]));
        assert!(should_skip(&["org.nspasteboard.concealedtype".into()]));
    }

    #[test]
    fn an_ordinary_text_copy_is_recorded() {
        assert!(!should_skip(&[
            "public.utf8-plain-text".into(),
            "NSStringPboardType".into(),
        ]));
        assert!(!should_skip(&[]));
    }

    #[test]
    fn whitespace_only_copies_are_dropped() {
        assert_eq!(normalize(""), None);
        assert_eq!(normalize("   \n\t "), None);
        assert_eq!(
            normalize("  hello  "),
            Some(("  hello  ".to_string(), false))
        );
    }

    #[test]
    fn oversized_text_is_cut_on_a_char_boundary() {
        // A multi-byte char straddling the cap must not panic the slice.
        let big = "á".repeat(MAX_TEXT_BYTES);
        let (text, truncated) = normalize(&big).expect("non-empty");
        assert!(truncated);
        assert!(text.len() <= MAX_TEXT_BYTES);
        assert!(big.starts_with(&text));
    }

    #[test]
    fn newest_entry_comes_first() {
        let mut ring = VecDeque::new();
        insert_entry(&mut ring, entry(1, "first"));
        insert_entry(&mut ring, entry(2, "second"));
        assert_eq!(ring[0].text, "second");
        assert_eq!(ring[1].text, "first");
    }

    #[test]
    fn recopying_promotes_instead_of_duplicating() {
        let mut ring = VecDeque::new();
        insert_entry(&mut ring, entry(1, "a"));
        insert_entry(&mut ring, entry(2, "b"));
        insert_entry(&mut ring, entry(3, "a"));
        assert_eq!(ring.len(), 2);
        assert_eq!(ring[0].text, "a");
        assert_eq!(ring[0].id, 3, "promoted entry carries the new id");
        assert_eq!(ring[1].text, "b");
    }

    /// Exercises the real `NSPasteboard` path end to end. `#[ignore]`d
    /// because it mutates the machine's actual clipboard, which no ordinary
    /// `cargo test` run should do. Run deliberately:
    ///
    /// ```text
    /// swiftc -O tests/fixtures/concealed_write.swift -o /tmp/concealed_write
    /// KLAUDIO_CONCEALED_BIN=/tmp/concealed_write \
    ///   cargo test -- --ignored --nocapture pasteboard
    /// ```
    #[cfg(target_os = "macos")]
    #[test]
    #[ignore = "mutates the real system clipboard"]
    fn pasteboard_roundtrip_records_text_but_never_a_concealed_write() {
        use std::process::{Command, Stdio};
        use std::io::Write as _;

        fn set_clipboard(text: &str) {
            let mut c = Command::new("pbcopy")
                .stdin(Stdio::piped())
                .spawn()
                .expect("pbcopy");
            c.stdin.as_mut().unwrap().write_all(text.as_bytes()).unwrap();
            c.wait().unwrap();
        }

        let before = read_change_count().expect("changeCount readable");

        // 1. An ordinary copy is seen and read back verbatim.
        set_clipboard("klaudio-clipboard-probe");
        let after = read_change_count().expect("changeCount readable");
        assert!(after > before, "changeCount must advance on a write");
        assert_eq!(
            read_pasteboard_string().as_deref(),
            Some("klaudio-clipboard-probe"),
        );

        // 2. A write carrying the password-manager marker advances the
        //    counter but must never yield content.
        let concealed = std::env::var("KLAUDIO_CONCEALED_BIN")
            .expect("set KLAUDIO_CONCEALED_BIN to the concealed-writer path");
        Command::new(&concealed)
            .arg("super-secret-value")
            .status()
            .expect("concealed writer runs");
        let after_concealed = read_change_count().expect("changeCount readable");
        assert!(after_concealed > after, "concealed write still bumps the counter");
        assert_eq!(
            read_pasteboard_string(),
            None,
            "a concealed write must never be recorded",
        );
    }

    #[test]
    fn the_ring_never_grows_past_its_cap() {
        let mut ring = VecDeque::new();
        for i in 0..(MAX_ENTRIES as u64 + 5) {
            insert_entry(&mut ring, entry(i, &format!("entry {i}")));
        }
        assert_eq!(ring.len(), MAX_ENTRIES);
        // Oldest fell off the back, newest is at the front.
        assert_eq!(ring[0].text, format!("entry {}", MAX_ENTRIES + 4));
        assert_eq!(ring[MAX_ENTRIES - 1].text, format!("entry {}", 5));
    }
}
